var testCaseDatabase = {
    "1": { "comment": "2+1 generations, 3 families where both families A and C are linked to B at generation-2 level",
           "graph":    [{ name :'f11', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'m11', outedges: [ {to: 'p1'} ], gender: "male" },
                        { name :'p1', outedges: [ {to: 'ch1'},{to: 'ch2'},{to: 'ch3'} ], relationship: true },
                        { name :'f13', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'m13', outedges: [ {to: 'p3'} ], gender: "male" },
                        { name :'p3', outedges: [ {to: 'ch7'},{to: 'ch8'},{to: 'ch9'} ], relationship: true },
                        { name :'f12', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'m12', outedges: [ {to: 'p2'} ], gender: "male" },
                        { name :'p2', outedges: [ {to: 'ch4'},{to: 'ch5'},{to: 'ch6'} ], relationship: true },
                        { name :'ch2', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'ch5', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'p4', outedges: [ {to: 'leaf1'} ], relationship: true },
                        { name :'ch4', outedges: [ {to: 'p5'} ], gender: "female" },
                        { name :'ch9', outedges: [ {to: 'p5'} ], gender: "male" },
                        { name :'p5', outedges: [ {to: 'leaf2'} ], relationship: true },
                        { name :'ch1', gender: "male" },
                        { name :'ch3', gender: "male" },
                        { name :'ch6', gender: "male" },
                        { name :'ch7', gender: "male" },
                        { name :'ch8', gender: "male" },
                        { name :'leaf1', gender: "male" },
                        { name :'leaf2', gender: "male" } ],
            "validate": { "maxCrossings": 0 },
            "runTime":  40
        },

    "1a": { "comment": "two families with a brotherA-sister1 + brotherB-sister2 relationships (min 1 edge crossing)",
            "graph":   [{ name :'f11', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'m11', outedges: [ {to: 'p1'} ], gender: "male" },
                        { name :'p1',  outedges: [ {to: 'ch1'},{to: 'ch2'},{to: 'ch3'} ], relationship: true },
                        { name :'f12', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'m12', outedges: [ {to: 'p2'} ], gender: "male" },
                        { name :'p2',  outedges: [ {to: 'ch4'},{to: 'ch5'} ], relationship: true },
                        { name :'ch2', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'ch5', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'p4',  outedges: [ {to: 'ch8'} ], relationship: true },
                        { name :'ch1', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'ch4', outedges: [ {to: 'p3'} ], gender: "male" },
                        { name :'p3',  outedges: [ {to: 'ch6'} ], relationship: true },
                        { name :'ch3', outedges: [ {to: 'p5'} ], gender: "female" },
                        { name :'m3',  outedges: [ {to: 'p5'} ], gender: "male" },
                        { name :'p5',  outedges: [ {to: 'ch7'} ], relationship: true },
                        { name :'ch7', gender: "male" },
                        { name :'ch6', gender: "male" },
                        { name :'ch8', gender: "male" } ],
            "validate": { "maxCrossings": 1 },
            "runTime":  40
        },

    "1b": { "comment": "same as TestCase1 + a few more children for a more complicated layout test",
           "graph":    [{ name :'f11', outedges: [ {to: 'p1'} ], sex: "female" },
                        { name :'m11', outedges: [ {to: 'p1'}, {to: 'p7'} ], sex: "male" },
                        { name :'p1', outedges: [ {to: 'ch1'},{to: 'ch2'},{to: 'ch3'} ], relationship: true },
                        { name :'f13', outedges: [ {to: 'p3'} ], sex: "female" },
                        { name :'m13', outedges: [ {to: 'p3'}, {to: 'p6'} ], sex: "male" },
                        { name :'p3', outedges: [ {to: 'ch7'},{to: 'ch8'},{to: 'ch9'} ], relationship: true },
                        { name :'f12', outedges: [ {to: 'p2'} ], sex: "female" },
                        { name :'m12', outedges: [ {to: 'p2'} ], sex: "male" },
                        { name :'p2', outedges: [ {to: 'ch4'},{to: 'ch5'},{to: 'ch6'} ], relationship: true },
                        { name :'ch2', outedges: [ {to: 'p4'} ], sex: "female" },
                        { name :'ch5', outedges: [ {to: 'p4'} ], sex: "male" },
                        { name :'p4', outedges: [ {to: 'leaf1'} ], relationship: true },
                        { name :'ch4', outedges: [ {to: 'p5'} ], sex: "female" },
                        { name :'ch9', outedges: [ {to: 'p5'} ], sex: "male" },
                        { name :'p5', outedges: [ {to: 'leaf2'} ], relationship: true },
                        { name :'ch1', sex: "male" },
                        { name :'ch3', sex: "male" },
                        { name :'ch6', sex: "male" },
                        { name :'ch7', sex: "male" },
                        { name :'ch8', sex: "male" },
                        { name :'leaf1', sex: "male" },
                        { name :'leaf2', sex: "male" },
                        { name : '_28', outedges: [ {to: 'p6'} ], sex: "female" },
                        { name : '_32', outedges: [ {to: 'p7'} ], sex: "female" },
                        { name :'p6', outedges: [ {to: 'leaf3'} ], relationship: true },
                        { name :'p7', outedges: [ {to: 'leaf4'} ], relationship: true },
                        { name :'leaf3', sex: "male" },
                        { name :'leaf4', sex: "male" } ],
            "validate": { "maxCrossings": 0 },
            "runTime":  60
        },

    "1c": { "comment": "two twins, one of them married to two sisters. Stored in serialized format",
            "graph":   [{"id":0,"prop":{"gender":"M","fName":"Jacob","lName":""},"outedges":[{"to":1}]},
                        {"id":1,"rel":true,"hub":true,"prop":{},"outedges":[{"to":3}]},
                        {"id":2,"prop":{"gender":"F"},"outedges":[{"to":1},{"to":5}]},
                        {"id":3,"chhub":true,"prop":{},"outedges":[{"to":4},{"to":9}]},
                        {"id":4,"prop":{"gender":"U","twinGroup":0},"outedges":[{"to":11},{"to":14}]},
                        {"id":5,"rel":true,"hub":true,"prop":{},"outedges":[{"to":7}]},
                        {"id":6,"prop":{"gender":"M"},"outedges":[{"to":5}]},
                        {"id":7,"chhub":true,"prop":{},"outedges":[{"to":8},{"to":10}]},
                        {"id":8,"prop":{"gender":"F", "fName":"Sister2"},"outedges":[{"to":11}]},
                        {"id":9,"prop":{"gender":"U","twinGroup":0}},
                        {"id":10,"prop":{"gender":"F", "fName":"Sister1"},"outedges":[{"to":14}]},
                        {"id":11,"rel":true,"hub":true,"prop":{},"outedges":[{"to":12}]},
                        {"id":12,"chhub":true,"prop":{},"outedges":[{"to":13}]},
                        {"id":13,"prop":{"gender":"U"}},
                        {"id":14,"rel":true,"hub":true,"prop":{},"outedges":[{"to":15}]},
                        {"id":15,"chhub":true,"prop":{},"outedges":[{"to":16}]},
                        {"id":16,"prop":{"gender":"U"}} ],
            "validate": { "maxCrossings": 1 },
            "runTime":  30
        },

    "3d": { "comment": "similar to 3c but with a more complicated relationship ('A' and '4' instead of 'A' and '9')",
            "graph":   [{ name :'1', outedges: [ {to: 'p1'} ], sex: "female" },
                        { name :'2', outedges: [ {to: 'p1'}, {to: 'p2'}, {to: 'p5'}, {to: 'p6'}], sex: "male" },
                        { name :'3', outedges: [ {to: 'p2'} ], sex: "female" },
                        { name :'4', outedges: [ {to: 'p3'}, {to: 'p8'} ], sex: "male" },
                        { name :'A', outedges: [ {to: 'p7'}, {to: 'p8'} ], sex: "female" },
                        { name :'B', outedges: [ {to: 'p7'} ], sex: "male" },
                        { name :'5', sex: "male" },
                        { name :'6', sex: "male" },
                        { name :'7', outedges: [ {to: 'p4'} ], sex: "female" },
                        { name :'8', outedges: [ {to: 'p4'} ], sex: "male" },
                        { name :'9', outedges: [ {to: 'p3'} ], sex: "female" },
                        { name :'10', outedges: [ {to: 'p5'} ], sex: "female" },
                        { name :'11', outedges: [ {to: 'p6'} ], sex: "female" },
                        { name :'12', sex: "male" },
                        { name :'13', sex: "male" },
                        { name :'D', sex: "male" },
                        { name :'14', sex: "female" },
                        { name :'E', sex: "male" },
                        { name :'15', sex: "female" },
                        { name :'C', sex: "male" },
                        { name :'p1', outedges: [ {to: '4'},{to: '5'},{to: '15'} ], relationship: true },
                        { name :'p2', outedges: [ {to: '6'},{to: '7'} ], relationship: true },
                        { name :'p3', outedges: [ {to: '10'}, {to: 'D'} ], relationship: true },
                        { name :'p4', outedges: [ {to: '11'} ], relationship: true },
                        { name :'p5', outedges: [ {to: '12'} ], relationship: true },
                        { name :'p6', outedges: [ {to: '13'}, {to: '14'} ], relationship: true },
                        { name :'p7', outedges: [ {to: '9'}, {to: 'C'} ], relationship: true },
                        { name :'p8', outedges: [ {to: 'E'} ], relationship: true } ],
            "validate": { "maxCrossings": 2 },
            "runTime":  230
           },
    };

