// comment:  any string
//
// graph:    list of objects, each object represents a node in the pedigree:
//            - nodes represent either persons or relationships. relationship nodes should have a "relationship" property set
//            - required properties: "name"
//            - optional properties: "outedges", "properties" and "gender" (all person nodes without gender are assigned "unknown" gender)
//            - outedges: list of objects; each object requires a "to" property and optional "weight" property (default weight is "1")
//            - all outedges for person nodes should go to the relationship nodes only
//            - names are given to relationship nodes only to simplify referrals; those names are dropped on import
//
// validate: suported checks:
//           - "maxCrossings" - integer; maximum number of edge crossings in the graph
//           - "sameRank"     - list of lists; nodes in the same sublist should be ranked on the same rank
//           - "neighbours"   - list of lists; nodes in the same sublist should be positioned next to each other
//                              (if there are more than two in the list any ordering of the nodes themselves is OK)
//
// runTime:  expected relative run time
//
// An optional format where nodes are defined by IDs instead of name is also supported (as in testcase "2c"); that
// is the format produced by graph serialization and supports nodes with no names (and is a bit more concise)
//
// Test cases:
//  1x           - basic pedigrees with no edge crossings, no multi-generational edges
//  2x           - some edge crossings, no multi-generational edges
//  3x           - special cases, such as twins or multiple relationships per person
//  4x           - various cases with multi-generational edges (including "I'm my own grandpa"), no crossings
//  5x           - most complicated, multi-generational edges + crossings + multiple relationships
//  Rankx        - case study: ranking when weights are defined
//  Abraham      - case study: "family of Abraham" - lots of intergenerationsl/caonsang. relationships, twins
//  Madeline_xx  - test cases from the Madeline test suite

var testCaseDatabase = {
    "1a": { "comment": "2+1 generations, 3 families where both families A and C are linked to B at generation-2 level",
           "graph":    [{ name :'f11', outedges: [ {to: 'p1'} ], gender: "female", properties: {"lifeStatus": "deceased"} },
                        { name :'m11', outedges: [ {to: 'p1'} ], gender: "male" },
                        { name :'p1', outedges: [ {to: 'ch1'},{to: 'ch2'},{to: 'ch3'} ], relationship: true },
                        { name :'f13', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'m13', outedges: [ {to: 'p3'} ], gender: "male" },
                        { name :'p3', outedges: [ {to: 'ch7'},{to: 'ch8'},{to: 'ch9'} ], relationship: true },
                        { name :'f12', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'m12', outedges: [ {to: 'p2'} ], gender: "male" },
                        { name :'p2', outedges: [ {to: 'ch4'},{to: 'ch5'},{to: 'ch6'} ], relationship: true },
                        { name :'ch2', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'ch5', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'p4', outedges: [ {to: 'leaf1'} ], relationship: true },
                        { name :'ch4', outedges: [ {to: 'p5'} ], gender: "female" },
                        { name :'ch9', outedges: [ {to: 'p5'} ], gender: "male" },
                        { name :'p5', outedges: [ {to: 'leaf2'} ], relationship: true },
                        { name :'ch1', gender: "male" },
                        { name :'ch3', gender: "male" },
                        { name :'ch6', gender: "male" },
                        { name :'ch7', gender: "male" },
                        { name :'ch8', gender: "male" },
                        { name :'leaf1', gender: "male" },
                        { name :'leaf2', gender: "male" } ],
            "validate": { "maxCrossings": 0,
                          "sameRank": [ ['f11','m11','f13','m13','f12','m12','p1', 'p2', 'p3' ],
                                        ['ch1','ch2','ch3','ch4','ch5','ch6','ch7','ch8','ch9'] ] },
            "runTime":  { best: 9, average: 20 }
          },

    "1b": { "comment": "same as 1a plus a few more children for a slightly more complicated layout test",
           "graph":    [{ name :'f11', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'m11', outedges: [ {to: 'p1'}, {to: 'p7'} ], gender: "male" },
                        { name :'p1', outedges: [ {to: 'ch1'},{to: 'ch2'},{to: 'ch3'} ], relationship: true },
                        { name :'f13', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'m13', outedges: [ {to: 'p3'}, {to: 'p6'} ], gender: "male" },
                        { name :'p3', outedges: [ {to: 'ch7'},{to: 'ch8'},{to: 'ch9'} ], relationship: true },
                        { name :'f12', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'m12', outedges: [ {to: 'p2'} ], gender: "male" },
                        { name :'p2', outedges: [ {to: 'ch4'},{to: 'ch5'},{to: 'ch6'} ], relationship: true },
                        { name :'ch2', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'ch5', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'p4', outedges: [ {to: 'leaf1'} ], relationship: true },
                        { name :'ch4', outedges: [ {to: 'p5'} ], gender: "female" },
                        { name :'ch9', outedges: [ {to: 'p5'} ], gender: "male" },
                        { name :'p5', outedges: [ {to: 'leaf2'} ], relationship: true },
                        { name :'ch1', gender: "male" },
                        { name :'ch3', gender: "male" },
                        { name :'ch6', gender: "male" },
                        { name :'ch7', gender: "male" },
                        { name :'ch8', gender: "male" },
                        { name :'leaf1', gender: "male" },
                        { name :'leaf2', gender: "male" },
                        { name : '_28', outedges: [ {to: 'p6'} ], gender: "female" },
                        { name : '_32', outedges: [ {to: 'p7'} ], gender: "female" },
                        { name :'p6', outedges: [ {to: 'leaf3'} ], relationship: true },
                        { name :'p7', outedges: [ {to: 'leaf4'} ], relationship: true },
                        { name :'leaf3', gender: "male" },
                        { name :'leaf4', gender: "male" } ],
            "validate": { "maxCrossings": 0 },
            "runTime":  { best: 40, average: 60 }
          },

    "2a": { "comment": "2+1 generations with brother-sister-brother-sister relationships (minimum one edge crossing)",
            "graph":   [{ name :'f1', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'m1', outedges: [ {to: 'p1'} ], gender: "male" },
                        { name :'p1', outedges: [ {to: 'ch1'},{to: 'ch2'},{to: 'ch3'} ], relationship: true },
                        { name :'f2', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'m2', outedges: [ {to: 'p2'} ], gender: "male" },
                        { name :'p2', outedges: [ {to: 'ch4'},{to: 'ch5'} ], relationship: true },
                        { name :'ch1', outedges: [ {to: 'p3'} ], gender: "male" },
                        { name :'ch4', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'p3', outedges: [ {to: 'ch6'} ], relationship: true },
                        { name :'ch2', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'ch3', gender: "male" },
                        { name :'ch5', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'ch6', gender: "male" },
                        { name :'p4', outedges: [ {to: 'ch7'} ], relationship: true },
                        { name :'ch7', gender: "male" } ],
            "validate": { "maxCrossings": 1 },
            "runTime":  { best: 7, average: 30 }
          },

    "2b": { "comment": "similar to 2a but with an extra relationship which should be correctly laid out with no additional edge crossings",
            "graph":   [{ name :'f11', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'m11', outedges: [ {to: 'p1'} ], gender: "male" },
                        { name :'p1',  outedges: [ {to: 'ch1'},{to: 'ch2'},{to: 'ch3'} ], relationship: true },
                        { name :'f12', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'m12', outedges: [ {to: 'p2'} ], gender: "male" },
                        { name :'p2',  outedges: [ {to: 'ch4'},{to: 'ch5'} ], relationship: true },
                        { name :'ch2', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'ch5', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'p4',  outedges: [ {to: 'ch8'} ], relationship: true },
                        { name :'ch1', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'ch4', outedges: [ {to: 'p3'} ], gender: "male" },
                        { name :'p3',  outedges: [ {to: 'ch6'} ], relationship: true },
                        { name :'ch3', outedges: [ {to: 'p5'} ], gender: "female" },
                        { name :'m3',  outedges: [ {to: 'p5'} ], gender: "male" },
                        { name :'p5',  outedges: [ {to: 'ch7'} ], relationship: true },
                        { name :'ch7', gender: "male" },
                        { name :'ch6', gender: "male" },
                        { name :'ch8', gender: "male" } ],
            "validate": { "maxCrossings": 1 },
            "runTime":  { best: 9, average: 30 }
          },

    "3a": { "comment": "two twins, one of them married to two sisters. Stored in serialized format",
            "graph":   [{"id":0,"prop":{"gender":"M","fName":"Jacob","lName":""},"outedges":[{"to":1}]},
                        {"id":1,"rel":true,"hub":true,"prop":{},"outedges":[{"to":3}]},
                        {"id":2,"prop":{"gender":"F"},"outedges":[{"to":1},{"to":5}]},
                        {"id":3,"chhub":true,"prop":{},"outedges":[{"to":4},{"to":9}]},
                        {"id":4,"prop":{"gender":"U","fName": "twin2","twinGroup":0},"outedges":[{"to":11},{"to":14}]},
                        {"id":5,"rel":true,"hub":true,"prop":{},"outedges":[{"to":7}]},
                        {"id":6,"prop":{"gender":"M"},"outedges":[{"to":5}]},
                        {"id":7,"chhub":true,"prop":{},"outedges":[{"to":8},{"to":10}]},
                        {"id":8,"prop":{"gender":"F", "fName":"Sister2"},"outedges":[{"to":11}]},
                        {"id":9,"prop":{"gender":"U","fName":"twin1","twinGroup":0}},
                        {"id":10,"prop":{"gender":"F", "fName":"Sister1"},"outedges":[{"to":14}]},
                        {"id":11,"rel":true,"hub":true,"prop":{},"outedges":[{"to":12}]},
                        {"id":12,"chhub":true,"prop":{},"outedges":[{"to":13}]},
                        {"id":13,"prop":{"gender":"U"}},
                        {"id":14,"rel":true,"hub":true,"prop":{},"outedges":[{"to":15}]},
                        {"id":15,"chhub":true,"prop":{},"outedges":[{"to":16}]},
                        {"id":16,"prop":{"gender":"U"}} ],
            "validate": { "maxCrossings": 1,
                          "neighbours": [ [4,9] ] },
            "runTime":  { best: 4, average: 20 }
          },

    "3b": { "comment": "3 relationships per person",
            "graph":   [{ name :'m11', outedges: [ {to: 'p1'} ], gender: "male" },
                        { name :'f11', outedges: [ {to: 'p1'},{to: 'p2'},{to: 'p3'} ], gender: "female" },
                        { name :'m12', outedges: [ {to: 'p2'} ], gender: "male" },
                        { name :'m13', outedges: [ {to: 'p3'} ], gender: "male" },
                        { name :'m21' },
                        { name :'m22' },
                        { name :'m23' },
                        { name :'p1', outedges: [ {to: 'm21'} ], relationship: true },
                        { name :'p2', outedges: [ {to: 'm22'} ], relationship: true },
                        { name :'p3', outedges: [ {to: 'm23'} ], relationship: true } ],
            "validate": { "maxCrossings": 1 },
            "runTime":  { best: 8, average: 20 }
          },

    "4a": { "comment": "\"I'm my own grandpa\" (a case of grandparent-grandchild relationship)",
            "graph":   [{ name :'1', outedges: [ {to: 'p1'} ], gender: "male", properties: {"lifeStatus": "deceased"}},
                        { name :'wife', outedges: [ {to: 'p1'}, {to: 'p3'} ], gender: "female" },
                        { name :'mother', outedges: [ {to: 'p2'} ], gender: "female", properties: {"lifeStatus": "deceased"}},
                        { name :'father', outedges: [ {to: 'p2'}, {to: 'p4'} ], gender: "male" },
                        { name :'5', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'me', outedges: [ {to: 'p3'} ], gender: "male" },
                        { name :'7', gender: "male" },
                        { name :'8', gender: "male" },
                        { name :'p1', outedges: [ {to: '5'} ], relationship: true },
                        { name :'p2', outedges: [ {to: 'me'} ], relationship: true },
                        { name :'p3', outedges: [ {to: '7'} ], relationship: true },
                        { name :'p4', outedges: [ {to: '8'} ], relationship: true } ],
            "validate": { "maxCrossings": 1 },
            "runTime":  { best: 8, average: 20 }
          },

    "4b": { "comment": "4a modified (an extra node was added) to test edge-crossing behavior in a special case",
            "graph":   [{ name :'1', outedges: [ {to: 'p1'} ], gender: "male", properties: {"lifeStatus": "deceased"} },
                        { name :'wife', outedges: [ {to: 'p1'}, {to: 'p3'} ], gender: "female" },
                        { name :'mother', outedges: [ {to: 'p2'} ], gender: "female", properties: {"lifeStatus": "deceased"} },
                        { name :'father', outedges: [ {to: 'p2'}, {to: 'p4'} ], gender: "male" },
                        { name :'5', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'me', outedges: [ {to: 'p3'} ], gender: "male" },
                        { name :'7', outedges: [ {to: 'p5'} ], gender: "male" },
                        { name :'8', gender: "male" },
                        { name :'9', outedges: [ {to: 'p5'} ], gender: "male" },
                        { name :'p1', outedges: [ {to: '5'} ], relationship: true },
                        { name :'p2', outedges: [ {to: 'me'} ], relationship: true },
                        { name :'p3', outedges: [ {to: '7'} ], relationship: true },
                        { name :'p4', outedges: [ {to: '8'} ], relationship: true },
                        { name :'p5', outedges: [ {to: '10'} ], relationship: true },
                        { name :'10', gender: "female" } ],
            "validate": { "maxCrossings": 1 },
            "runTime":  { best: 8, average: 20 }
          },

    "4c": { "comment": "a case of consanguineous grandparent-grandchild relationship. No edge crossings",
            "graph":   [{ name :'f11', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'m11', outedges: [ {to: 'p1'} ], gender: "male" },
                        { name :'f12', outedges: [ {to: 'p2'}, {to:'p4'} ], gender: "female" },
                        { name :'m12', outedges: [ {to: 'p2'} ], gender: "male" },
                        { name :'m21', gender: "male" },
                        { name :'m22', outedges: [ {to: 'p3'} ], gender: "male" },
                        { name :'f21', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'m23', gender: "male" },
                        { name :'m31', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'f41', gender: "female" },
                        { name :'m41', gender: "male" },
                        { name :'p1', outedges: [ {to: 'm21'},{to: 'm22'} ], relationship: true },
                        { name :'p2', outedges: [ {to: 'f21'},{to: 'm23'} ], relationship: true },
                        { name :'p3', outedges: [ {to: 'm31'} ], relationship: true },
                        { name :'p4', outedges: [ {to: 'f41'},{to: 'm41'} ], relationship: true } ],
            "validate": { "maxCrossings": 0,
                          "sameRank":     [ ['p4','m31'], ['f12','m11','m12','f11'] ] },
            "runTime":  { best: 8, average: 20 }
          },

    "4d": { "comment": "4+1 generations, two multi-generational edges. No edge crossings",
            "graph":   [{ name :'1', outedges: [ {to: 'p1'} ], gender: "male"},
                        { name :'2', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'p1', outedges: [ {to: '6'},{to: '5'},{to: '4'},{to: '3'} ], rel: true },
                        { name :'3', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'4', outedges: [ {to: 'p2'} ], gender: "male" },
                        { name :'p2', outedges: [ {to: '8'},{to: '7'} ], rel: true },
                        { name :'6', gender: "male" },
                        { name :'5', outedges: [ {to: 'p3'} ], gender: "male" },
                        { name :'8', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'7', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'p3', outedges: [ {to: '10'}, {to: '9'} ], rel: true },
                        { name :'9', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'10', gender: "male" },
                        { name :'11', gender: "female" },
                        { name :'p4', outedges: [ {to: '11'} ], rel: true } ],
            "validate": { "maxCrossings": 0 },
            "runTime":  { best: 7, average: 20 }
          },

    "5a": { "comment": "a relationship between one person and both a parent and parent's child",
            "graph":   [{ name :'1', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'2', outedges: [ {to: 'p1'} ], gender: "male" },
                        { name :'3', outedges: [ {to: 'p2'}, {to:'p3'} ], gender: "female" },
                        { name :'4', outedges: [ {to: 'p2'} ], gender: "male" },
                        { name :'5', gender: "male" },
                        { name :'6', gender: "male" },
                        { name :'7', outedges: [ {to: 'p3'},{to: 'p4'} ], gender: "male" },
                        { name :'8', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'9', gender: "male" },
                        { name :'10', gender: "male" },
                        { name :'11', gender: "male" },
                        { name :'p1', outedges: [ {to: '5'},{to: '6'},{to: '7'} ], relationship: true },
                        { name :'p2', outedges: [ {to: '8'},{to: '9'} ], relationship: true },
                        { name :'p3', outedges: [ {to: '10'} ], relationship: true },
                        { name :'p4', outedges: [ {to: '11'} ], relationship: true } ],
            "validate": { "maxCrossings": 1 },
            "runTime":  { best: 17, average: 50 }
          },

    "5b": { "comment": "3+1 generations with two grandparent-grandchild relationships. No edge crossings.",
            "graph":   [{ name :'1', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'2', outedges: [ {to: 'p1'}, {to: 'p2'}, {to: 'p5'}, {to: 'p6'}], gender: "male" },
                        { name :'3', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'4', outedges: [ {to: 'p3'} ], gender: "male" },
                        { name :'5', gender: "male" },
                        { name :'6', gender: "male" },
                        { name :'7', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'8', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'9', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'10', outedges: [ {to: 'p5'} ], gender: "female" },
                        { name :'11', outedges: [ {to: 'p6'} ], gender: "female" },
                        { name :'12', gender: "male" },
                        { name :'13', gender: "male" },
                        { name :'14', gender: "female" },
                        { name :'15', gender: "female" },
                        { name :'p1', outedges: [ {to: '4'},{to: '5'},{to: '15'} ], relationship: true },
                        { name :'p2', outedges: [ {to: '6'},{to: '7'} ], relationship: true },
                        { name :'p3', outedges: [ {to: '10'} ], relationship: true },
                        { name :'p4', outedges: [ {to: '11'} ], relationship: true },
                        { name :'p5', outedges: [ {to: '12'} ], relationship: true },
                        { name :'p6', outedges: [ {to: '13'}, {to: '14'} ], relationship: true } ],
            "validate": { "maxCrossings": 0 },
            "runTime":  { best: 20, average: 60 }
          },

    "5c": { "comment": "similar to 5b but with more root nodes",
            "graph":   [{ name :'1', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'2', outedges: [ {to: 'p1'}, {to: 'p2'}, {to: 'p5'}, {to: 'p6'}], gender: "male" },
                        { name :'3', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'4', outedges: [ {to: 'p3'} ], gender: "male" },
                        { name :'A', outedges: [ {to: 'p7'}, {to: 'p8'} ], gender: "female" },
                        { name :'B', outedges: [ {to: 'p7'} ], gender: "male" },
                        { name :'5', gender: "male" },
                        { name :'6', gender: "male" },
                        { name :'7', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'8', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'9', outedges: [ {to: 'p3'}, {to: 'p8'} ], gender: "female" },
                        { name :'10', outedges: [ {to: 'p5'} ], gender: "female" },
                        { name :'11', outedges: [ {to: 'p6'} ], gender: "female" },
                        { name :'12', gender: "male" },
                        { name :'13', gender: "male" },
                        { name :'D', gender: "male" },
                        { name :'14', gender: "female" },
                        { name :'E', gender: "male" },
                        { name :'15', gender: "female" },
                        { name :'C', gender: "male" },
                        { name :'p1', outedges: [ {to: '4'},{to: '5'},{to: '15'} ], relationship: true },
                        { name :'p2', outedges: [ {to: '6'},{to: '7'} ], relationship: true },
                        { name :'p3', outedges: [ {to: '10'}, {to: 'D'} ], relationship: true },
                        { name :'p4', outedges: [ {to: '11'} ], relationship: true },
                        { name :'p5', outedges: [ {to: '12'} ], relationship: true },
                        { name :'p6', outedges: [ {to: '13'}, {to: '14'} ], relationship: true },
                        { name :'p7', outedges: [ {to: '9'}, {to: 'C'} ], relationship: true },
                        { name :'p8', outedges: [ {to: 'E'} ], relationship: true } ],
            "validate": { "maxCrossings": 0 },
            "runTime":  { best: 188, average: 220 }
          },

    "5d": { "comment": "similar to 5c but with a more complicated relationship ('A' and '4' instead of 'A' and '9')",
            "graph":   [{ name :'1', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'2', outedges: [ {to: 'p1'}, {to: 'p2'}, {to: 'p5'}, {to: 'p6'}], gender: "male" },
                        { name :'3', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'4', outedges: [ {to: 'p3'}, {to: 'p8'} ], gender: "male" },
                        { name :'A', outedges: [ {to: 'p7'}, {to: 'p8'} ], gender: "female" },
                        { name :'B', outedges: [ {to: 'p7'} ], gender: "male" },
                        { name :'5', gender: "male" },
                        { name :'6', gender: "male" },
                        { name :'7', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'8', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'9', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'10', outedges: [ {to: 'p5'} ], gender: "female" },
                        { name :'11', outedges: [ {to: 'p6'} ], gender: "female" },
                        { name :'12', gender: "male" },
                        { name :'13', gender: "male" },
                        { name :'D', gender: "male" },
                        { name :'14', gender: "female" },
                        { name :'E', gender: "male" },
                        { name :'15', gender: "female" },
                        { name :'C', gender: "male" },
                        { name :'p1', outedges: [ {to: '4'},{to: '5'},{to: '15'} ], relationship: true },
                        { name :'p2', outedges: [ {to: '6'},{to: '7'} ], relationship: true },
                        { name :'p3', outedges: [ {to: '10'}, {to: 'D'} ], relationship: true },
                        { name :'p4', outedges: [ {to: '11'} ], relationship: true },
                        { name :'p5', outedges: [ {to: '12'} ], relationship: true },
                        { name :'p6', outedges: [ {to: '13'}, {to: '14'} ], relationship: true },
                        { name :'p7', outedges: [ {to: '9'}, {to: 'C'} ], relationship: true },
                        { name :'p8', outedges: [ {to: 'E'} ], relationship: true } ],
            "validate": { "maxCrossings": 2 },
            "runTime":  { best: 195, average: 230}
          },

    "5e": { "comment": "similar to 5d but with a few additional nodes",
            "graph":   [{ name :'1', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'2', outedges: [ {to: 'p1'}, {to: 'p2'}, {to: 'p5'}, {to: 'p6'}], gender: "male" },
                        { name :'3', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'4', outedges: [ {to: 'p3'}, {to: 'p8'} ], gender: "male" },
                        { name :'A', outedges: [ {to: 'p7'}, {to: 'p8'} ], gender: "female" },
                        { name :'B', outedges: [ {to: 'p7'} ], gender: "male" },
                        { name :'5', gender: "male" },
                        { name :'6', gender: "male" },
                        { name :'7', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'8', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'9', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'10', outedges: [ {to: 'p5'} ], gender: "female" },
                        { name :'11', outedges: [ {to: 'p6'} ], gender: "female" },
                        { name :'12', gender: "male" },
                        { name :'13', gender: "male" },
                        { name :'D', gender: "male" },
                        { name :'14', gender: "female" },
                        { name :'E', gender: "male" },
                        { name :'15', gender: "female" },
                        { name :'C', outedges: [ {to: 'p9'} ], gender: "male" },
                        { name :'CA', outedges: [ {to: 'p9'} ], gender: "female" },
                        { name :'CB', gender: "male" },
                        { name :'p1', outedges: [ {to: '4'},{to: '5'},{to: '15'} ], relationship: true },
                        { name :'p2', outedges: [ {to: '6'},{to: '7'} ], relationship: true },
                        { name :'p3', outedges: [ {to: '10'}, {to: 'D'} ], relationship: true },
                        { name :'p4', outedges: [ {to: '11'} ], relationship: true },
                        { name :'p5', outedges: [ {to: '12'} ], relationship: true },
                        { name :'p6', outedges: [ {to: '13'}, {to: '14'} ], relationship: true },
                        { name :'p7', outedges: [ {to: '9'}, {to: 'C'} ], relationship: true },
                        { name :'p8', outedges: [ {to: 'E'} ], relationship: true },
                        { name :'p9', outedges: [ {to: 'CB'} ], relationship: true } ],
            "validate": { "maxCrossings": 2 },
            "runTime":  { best: 240, average: 270 }
          },

    "Rank1": { "comment": "a graph with two mid-level parentless nodes which should be ranked on the same\n\
              level with their partners. Children should be placed next to each other, when possible:\n\
              e.g. {m33, m34, f31} or {f31, m34, m33} but not {m33, f31, m34}",
            "graph":   [{ name :'m12', outedges: [ {to: 'p2'} ], gender: "male" },
                        { name :'f12', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'m33', gender: "male" },
                        { name :'m34', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'f31', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'f41', outedges: [ {to: 'p5'} ], gender: "female" },
                        { name :'m41', outedges: [ {to: 'p5'} ], gender: "male" },
                        { name :'m42', gender: "male" },
                        { name :'f51', gender: "female" },
                        { name :'m51', gender: "male" },
                        { name :'p2', outedges: [ {to: 'm33'}, {to: 'm34'} ], relationship: true },
                        { name :'p4', outedges: [ {to: 'm41'}, {to: 'm42'} ], relationship: true },
                        { name :'p5', outedges: [ {to: 'f51'}, {to: 'm51'} ], relationship: true } ],
            "validate": { "maxCrossings": 0,
                          "neighbours": [ [ 'm33', 'm34'] ] },
            "runTime":  { best: 2, average: 15 }
           },

    "Rank2": { "comment": "two components connected by two multi-rank edges. One of those should be shortened.\n\
              (when edges have no weights the shorter m12 -> p3 edge should be shortened)\n\
              also all nodes with no parents should be ranked on the same level with their partners",
            "graph":   [{ name :'m11', outedges: [ {to: 'p1'} ], gender: "male" },
                        { name :'f11', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'m12', outedges: [ {to: 'p2'}, {to: 'p3'} ], gender: "male" },
                        { name :'f12', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'m21', outedges: [ {to: 'p6'} ],gender: "male" },
                        { name :'f21', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'m31', gender: "male" },
                        { name :'m32', gender: "male" },
                        { name :'m33', gender: "male" },
                        { name :'m34', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'f31', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'f41', outedges: [ {to: 'p5'} ], gender: "female" },
                        { name :'m41', outedges: [ {to: 'p5'} ], gender: "male" },
                        { name :'m42', gender: "male" },
                        { name :'f51', outedges: [ {to: 'p6'} ], gender: "female" },
                        { name :'m51', gender: "male" },
                        { name :'f61', gender: "female" },
                        { name :'f62', gender: "female" },
                        { name :'p1', outedges: [ {to: 'm21'}, {to: 'f21'} ], relationship: true },
                        { name :'p2', outedges: [ {to: 'm33'}, {to: 'm34'} ], relationship: true },
                        { name :'p3', outedges: [ {to: 'm31'}, {to: 'm32'} ], relationship: true },
                        { name :'p4', outedges: [ {to: 'm41'}, {to: 'm42'} ], relationship: true },
                        { name :'p5', outedges: [ {to: 'f51'}, {to: 'm51'} ], relationship: true },
                        { name :'p6', outedges: [ {to: 'f61'}, {to: 'f62'} ], relationship: true } ],
            "validate": { "maxCrossings": 0,
                          "sameRank": [ ['m12','f21'] ] },
            "runTime":  { best: 12, average: 30 }
           },

    "Rank3": { "comment": "similar to Rank2, but m21->p6 edge has higher weight and will be shortened instead of m12->p3",
            "graph":   [{ name :'m11', outedges: [ {to: 'p1'} ], gender: "male" },
                        { name :'f11', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'m12', outedges: [ {to: 'p2'}, {to: 'p3'} ], gender: "male" },
                        { name :'f12', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'m21', outedges: [ {to: 'p6', weight: 10} ],gender: "male" },
                        { name :'f21', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'m31', gender: "male" },
                        { name :'m32', gender: "male" },
                        { name :'m33', gender: "male" },
                        { name :'m34', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'f31', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'f41', outedges: [ {to: 'p5'} ], gender: "female" },
                        { name :'m41', outedges: [ {to: 'p5'} ], gender: "male" },
                        { name :'m42', gender: "male" },
                        { name :'f51', outedges: [ {to: 'p6'} ], gender: "female" },
                        { name :'m51', gender: "male" },
                        { name :'f61', gender: "female" },
                        { name :'f62', gender: "female" },
                        { name :'p1', outedges: [ {to: 'm21'}, {to: 'f21'} ], relationship: true },
                        { name :'p2', outedges: [ {to: 'm33'}, {to: 'm34'} ], relationship: true },
                        { name :'p3', outedges: [ {to: 'm31'}, {to: 'm32'} ], relationship: true },
                        { name :'p4', outedges: [ {to: 'm41'}, {to: 'm42'} ], relationship: true },
                        { name :'p5', outedges: [ {to: 'f51'}, {to: 'm51'} ], relationship: true },
                        { name :'p6', outedges: [ {to: 'f61'}, {to: 'f62'} ], relationship: true } ],
            "validate": { "maxCrossings": 0,
                          "sameRank": [ ['m21','f51'] ]  },
            "runTime":  { best: 17, average: 50 }
           },

    "Madeline_CS_002": { "comment": "CS_002 from Madeline test suite",
            "graph":   [{ name :'1', outedges: [ {to: 'p1'} ], gender: "male"},
                        { name :'2', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'p1', outedges: [ {to: '6'},{to: '5'},{to: '3'} ], rel: true },
                        { name :'3', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'4', outedges: [ {to: 'p2'} ], gender: "male" },
                        { name :'p2', outedges: [ {to: '8'},{to: '7'} ], rel: true },
                        { name :'6', gender: "male" },
                        { name :'5', outedges: [ {to: 'p3'} ], gender: "male" },
                        { name :'8', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'7', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'p3', outedges: [ {to: '10'}, {to: '9'} ], rel: true },
                        { name :'9', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'10', gender: "male" },
                        { name :'11', gender: "female" },
                        { name :'p4', outedges: [ {to: '11'} ], rel: true } ],
            "validate": { "maxCrossings": 0 },
            "runTime":  { best: 5, average: 30 }
           },

    "Madeline_CS_004": { "comment": "CS_004 from Madeline test suite",
            "graph":   [{ name :'1', outedges: [ {to: 'p1'} ], gender: "male" },
                        { name :'2', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'p1', outedges: [ {to: '4'},{to: '5'} ], relationship: true },
                        { name :'5', outedges: [ {to: 'p2'} ], gender: "male" },
                        { name :'3', outedges: [ {to: 'p3'} ], gender: "male" },
                        { name :'4', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'p2', outedges: [ {to: '8'} ], relationship: true },
                        { name :'7', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'p3', outedges: [ {to: '7'}, {to: '6'} ], relationship: true },
                        { name :'6', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'10', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'p4', outedges: [ {to: '9'} ], relationship: true },
                        { name :'8', outedges: [ {to: 'p5'} ], gender: "male" },
                        { name :'9', outedges: [ {to: 'p5'} ], gender: "female" },
                        { name :'p5', outedges: [ {to: '11'}, {to: '12'}, {to: '13'} ], relationship: true },
                        { name :'11', gender: "male" },
                        { name :'12', gender: "male" },
                        { name :'13', gender: "male" } ],
            "validate": { "maxCrossings": 0 },
            "runTime":  { best: 6, average: 40 }
           },

    "Madeline_CS_009": { "comment": "CS_009 from Madeline test suite",
            "graph":   [{ name :'68', outedges: [ {to: 'p1'} ], gender: "male" },
                        { name :'69', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'p1', outedges: [ {to: '70'},{to: '71'} ], relationship: true },
                        { name :'70', outedges: [ {to: 'p2'} ], gender: "male" },
                        { name :'71', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'72', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'75', outedges: [ {to: 'p3'} ], gender: "male" },
                        { name :'p2', outedges: [ {to: '74'}, {to: '73'} ], relationship: true },
                        { name :'p3', outedges: [ {to: '76'}, {to: '77'} ], relationship: true },
                        { name :'81', outedges: [ {to: 'p5'} ], gender: "male" },
                        { name :'78', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'73', outedges: [ {to: 'p4'} ], gender: "male" },
                        { name :'77', outedges: [ {to: 'p5'} ], gender: "female" },
                        { name :'74', gender: "female" },
                        { name :'76', gender: "male" },
                        { name :'p4', outedges: [ {to: '80'}, {to: '79'} ], relationship: true },
                        { name :'p5', outedges: [ {to: '82'}, {to: '83'} ], relationship: true },
                        { name :'88', outedges: [ {to: 'p7'} ], gender: "female" },
                        { name :'84', outedges: [ {to: 'p6'} ], gender: "male" },
                        { name :'82', outedges: [ {to: 'p7'} ], gender: "male" },
                        { name :'80', outedges: [ {to: 'p6'} ], gender: "female" },
                        { name :'79', gender: "male" },
                        { name :'83', gender: "female" },
                        { name :'p6', outedges: [ {to: '85'}, {to: '86'}, {to: '87'} ], relationship: true },
                        { name :'p7', outedges: [ {to: '89'}, {to: '90'}, {to: '91'}, {to: '92'} ], relationship: true },
                        { name :'91', outedges: [ {to: 'p8'} ], gender: "male" },
                        { name :'86', outedges: [ {to: 'p8'} ], gender: "female" },
                        { name :'85', gender: "female" },
                        { name :'87', gender: "female" },
                        { name :'89', gender: "male" },
                        { name :'90', gender: "male" },
                        { name :'92', gender: "male" },
                        { name :'p8', outedges: [ {to: '94'}, {to: '95'}, {to: '96'} ], relationship: true },
                        { name :'94', gender: "male" },
                        { name :'95', gender: "male" },
                        { name :'96', gender: "female" } ],
            "validate": { "maxCrossings": 0 },
            "runTime":  { best: 14, average: 40 }
           },

    /*"Madeline_MS_004": { "comment": "MS_004 from Madeline test suite",
            "graph":   [{ name :'1', outedges: [ {to: 'p1'} ], gender: "male" },
                        { name :'2', outedges: [ {to: 'p1'} ], gender: "female" },
                        { name :'p1', outedges: [ {to: 'c1'},{to: 'c2'},{to: 'c3'},{to: 'c4'},{to: 'c5'},{to: 'c6'},{to: 'c7'},{to: 'c8'} ], relationship: true },
                        { name :'c1', gender: "female" },
                        { name :'c2', gender: "female" },
                        { name :'c3', outedges: [ {to: 'p2'},{to: 'p3'},{to: 'p4'},{to: 'p5'},{to: 'p6'},{to: 'p7'},{to: 'p8'},{to: 'p9'},{to: 'p10'},{to: 'p11'},{to: 'p12'} ], gender: "male" },
                        { name :'c4', gender: "female" },
                        { name :'c5', gender: "male" },
                        { name :'c6', gender: "male" },
                        { name :'c7', gender: "male" },
                        { name :'c8', gender: "male" },
                        { name :'w1', outedges: [ {to: 'p2'} ], gender: "female" },
                        { name :'w2', outedges: [ {to: 'p3'} ], gender: "female" },
                        { name :'w3', outedges: [ {to: 'p4'} ], gender: "female" },
                        { name :'w4', outedges: [ {to: 'p5'} ], gender: "female" },
                        { name :'w5', outedges: [ {to: 'p6'} ], gender: "female" },
                        { name :'w6', outedges: [ {to: 'p7'} ], gender: "female" },
                        { name :'w7', outedges: [ {to: 'p8'} ], gender: "female" },
                        { name :'w8', outedges: [ {to: 'p9'} ], gender: "female" },
                        { name :'w9', outedges: [ {to: 'p10'} ], gender: "female" },
                        { name :'w10', outedges: [ {to: 'p11'} ], gender: "female" },
                        { name :'w11', outedges: [ {to: 'p12'} ], gender: "female" },
                        { name :'p2', outedges: [ {to: 'l1'} ], relationship: true },
                        { name :'p3', outedges: [ {to: 'l2'},{to: 'l3'},{to: 'l4'},{to: 'l5'} ], relationship: true },
                        { name :'p4', outedges: [ {to: 'l6'} ], relationship: true },
                        { name :'p5', outedges: [ {to: 'l7'} ], relationship: true },
                        { name :'p6', outedges: [ {to: 'l8'},{to: 'l9'} ], relationship: true },
                        { name :'p7', outedges: [ {to: 'l10'} ], relationship: true },
                        { name :'p8', outedges: [ {to: 'l11'},{to: 'l12'} ], relationship: true },
                        { name :'p9', outedges: [ {to: 'l13'} ], relationship: true },
                        { name :'p10', outedges: [ {to: 'l14'},{to: 'l15'} ], relationship: true },
                        { name :'p11', outedges: [ {to: 'l16'},{to: 'l17'} ], relationship: true },
                        { name :'p12', outedges: [ {to: 'l18'},{to: 'l19'} ], relationship: true },
                        { name :'l1', gender: "male" },
                        { name :'l2', gender: "male" },
                        { name :'l3', gender: "male" },
                        { name :'l4', gender: "male" },
                        { name :'l5', gender: "male" },
                        { name :'l6', gender: "male" },
                        { name :'l7', gender: "male" },
                        { name :'l8', gender: "male" },
                        { name :'l9', gender: "male" },
                        { name :'l10', gender: "male" },
                        { name :'l11', gender: "male" },
                        { name :'l12', gender: "male" },
                        { name :'l13', gender: "male" },
                        { name :'l14', gender: "male" },
                        { name :'l15', gender: "male" },
                        { name :'l16', gender: "male" },
                        { name :'l17', gender: "male" },
                        { name :'l18', gender: "male" },
                        { name :'l19', gender: "male" } ],
            "validate": {},
            "runTime":  { best: 58, average: 90 }
           }*/

    "Abraham": { "comment": "\"The family of Abraham\" (stored in serialized format)",
            "graph":   [{id: 0, prop: {gender: 'M', fName: 'Terah', lName: ''}, outedges: [{to: 1}]},
                        {id: 1, rel: true, hub: true, prop: {}, outedges: [{to: 3}]}, {id: 2, prop: {gender: 'F'}, outedges: [{to: 1}]},
                        {id: 3, chhub: true, prop: {}, outedges: [{to: '5'}, {to: 6}, {to: 4}]},
                        {id: 4, prop: {gender: 'M', fName: 'Abram'}, outedges: [{to: 7}, {to: 11}]},
                        {id: 5, prop: {gender: 'M', fName: 'Haran'}, outedges: [{to: 16}]},
                        {id: 6, prop: {gender: 'M', fName: 'Nahor'}, outedges: [{to: 21}]},
                        {id: 7, rel: true, hub: true, prop: {}, outedges: [{to: 9}]},
                        {id: 8, prop: {gender: 'F', fName: 'Sarai'}, outedges: [{to: 7}]},
                        {id: 9, chhub: true, prop: {}, outedges: [{to: 10}]},
                        {id: 10, prop: {gender: 'M', fName: 'Isaac'}, outedges: [{to: 34}]},
                        {id: 11, rel: true, hub: true, prop: {}, outedges: [{to: 13}]},
                        {id: 12, prop: {gender: 'F', fName: 'Hagar'}, outedges: [{to: 11}]},
                        {id: 13, chhub: true, prop: {}, outedges: [{to: 14}]},
                        {id: 14, prop: {gender: 'M', fName: 'Ishmael'}},
                        {id: 15, prop: {gender: 'F', fName: 'Milcah'}, outedges: [{to: 21}]},
                        {id: 16, rel: true, hub: true, prop: {}, outedges: [{to: 18}]},
                        {id: 17, prop: {gender: 'F'}, outedges: [{to: 16}]},
                        {id: 18, chhub: true, prop: {}, outedges: [{to: 19}, {to: 15}]},
                        {id: 19, prop: {gender: 'M', fName: 'Lot'}, outedges: [{to: 45}, {to: 48}, {to: 51}]},
                        {id: 20, prop: {gender: 'F', fName: 'Daughter 1'}, outedges: [{to: 45}]},
                        {id: 21, rel: true, hub: true, prop: {}, outedges: [{to: 22}]},
                        {id: 22, chhub: true, prop: {}, outedges: [{to: 23}]},
                        {id: 23, prop: {gender: 'M', fName: 'Bethuel'}, outedges: [{to: 24}]},
                        {id: 24, rel: true, hub: true, prop: {}, outedges: [{to: 26}]},
                        {id: 25, prop: {gender: 'F'}, outedges: [{to: 24}]},
                        {id: 26, chhub: true, prop: {}, outedges: [{to: 27}, {to: 28}]},
                        {id: 27, prop: {gender: 'M', fName: 'Laban'}, outedges: [{to: 30}]},
                        {id: 28, prop: {gender: 'F', fName: 'Rebekah'}, outedges: [{to: 34}]},
                        {id: 29, prop: {gender: 'F', fName: 'Leah'}, outedges: [{to: 41}]},
                        {id: 30, rel: true, hub: true, prop: {}, outedges: [{to: 32}]},
                        {id: 31, prop: {gender: 'F'}, outedges: [{to: 30}]},
                        {id: 32, chhub: true, prop: {}, outedges: [{to: 29}, {to: 33}]},
                        {id: 33, prop: {gender: 'F', fName: 'Rachel'}, outedges: [{to: 38}]},
                        {id: 34, rel: true, hub: true, prop: {}, outedges: [{to: 35}]},
                        {id: 35, chhub: true, prop: {}, outedges: [{to: 36}, {to: 37}]},
                        {id: 36, prop: {gender: 'M', fName: 'Jacob', twinGroup: 0, monozygotic: true}, outedges: [{to: 38}, {to: 41}]},
                        {id: 37, prop: {gender: 'M', fName: 'Esau', twinGroup: 0, monozygotic: true}},
                        {id: 38, rel: true, hub: true, prop: {}, outedges: [{to: 39}]},
                        {id: 39, chhub: true, prop: {}, outedges: [{to: 40}]},
                        {id: 40, prop: {gender: 'U'}},
                        {id: 41, rel: true, hub: true, prop: {}, outedges: [{to: 42}]},
                        {id: 42, chhub: true, prop: {}, outedges: [{to: 43}]},
                        {id: 43, prop: {gender: 'U'}},
                        {id: 44, prop: {gender: 'F', fName: 'Daughter 2'}, outedges: [{to: 48}]},
                        {id: 45, rel: true, hub: true, prop: {}, outedges: [{to: 46}]},
                        {id: 46, chhub: true, prop: {}, outedges: [{to: 47}]},
                        {id: 47, prop: {gender: 'M', fName: 'Moabites'}},
                        {id: 48, rel: true, hub: true, prop: {}, outedges: [{to: 49}]},
                        {id: 49, chhub: true, prop: {}, outedges: [{to: 50}]},
                        {id: 50, prop: {gender: 'M', fName: 'Menanites'}},
                        {id: 51, rel: true, hub: true, prop: {}, outedges: [{to: 53}]},
                        {id: 52, prop: {gender: 'F'}, outedges: [{to: 51}]}, {id: 53, chhub: true, prop: {}, outedges: [{to: 20}, {to: 44}]}],
            "validate": { "maxCrossings": 10 },
            "runTime":  { best: 295, average: 350 }
          }
};

